"""update order model

Revision ID: 2b5c74396368
Revises: b769c7578c33
Create Date: 2025-08-20 17:58:36.760864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5c74396368'
down_revision: Union[str, Sequence[str], None] = 'b769c7578c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_phone', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('buyer_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buyer_address')
    op.drop_column('orders', 'buyer_phone')
    # ### end Alembic commands ###
