"""add expired_at blacklist

Revision ID: 707c087bdc67
Revises: c5902c92f3d8
Create Date: 2025-08-21 10:08:08.878230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707c087bdc67'
down_revision: Union[str, Sequence[str], None] = 'c5902c92f3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist_tokens', 'expires_at')
    # ### end Alembic commands ###
