"""rename customer_id to buyer_id in orders

Revision ID: 8dffc400220f
Revises: d19ca0ab2174
Create Date: 2025-08-19 17:15:56.866627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dffc400220f'
down_revision: Union[str, Sequence[str], None] = 'd19ca0ab2174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'users', ['customer_id'], ['id'])
    op.drop_column('orders', 'buyer_id')
    # ### end Alembic commands ###
