"""add public_id in category model

Revision ID: b769c7578c33
Revises: 8dffc400220f
Create Date: 2025-08-20 12:00:45.467134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b769c7578c33'
down_revision: Union[str, Sequence[str], None] = '8dffc400220f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'public_id')
    # ### end Alembic commands ###
